function(download_onnxruntime)
  include(FetchContent)
  set(ONNXRUNTIME_VERSION "1.23.2")

  message(STATUS "CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
  message(STATUS "CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")

  if(${CMAKE_SYSTEM_NAME} STREQUAL "Linux")
    if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL x86_64)
      if(ENABLE_ONNX_EXECUTOR_GPU)
        include(onnxruntime-linux-x86_64-gpu)
      else()
        include(onnxruntime-linux-x86_64)
      endif()
    else()
      #TODO(lianghu): support other platform
      message(FATAL_ERROR "Only support x86_64 now")
    endif()
  elseif(${CMAKE_SYSTEM_NAME} STREQUAL "Darwin")
    if(${CMAKE_SYSTEM_PROCESSOR} STREQUAL "arm64")
      include(onnxruntime-osx-arm64)
    else()
      message(FATAL_ERROR "Only support ${CMAKE_SYSTEM_NAME}-arm64 now")
    endif()
  else()
    message(FATAL_ERROR "Only support Linux and Drawin now")
  endif()
endfunction()

download_onnxruntime()
